Feature#pickup price by customer
CreadixGal/aeksion pull request #108
Opened 2023-02-02 16:43 UTC by lucas94gv

Add field to database and automatic assignation on create rate

2023-02-02 16:44 UTC, lucas94gv commented
@ciscoLegrand añade aqui cando podas duas cousas. Alineacion da tabla do index de customers e o crear un rate e seleccionar pickup que non sea readonly o input de price xa que collera automatico o que estableza o customer

2023-02-02 21:43 UTC, ciscoLegrand requested changes

2023-02-02 21:43 UTC, ciscoLegrand commented on app/views/customers/index.html.erb
> +            <div class="flex flex-1 justify-center items center">
@lucas94gv entendo que dis por aqui o de alinear a tabla do index??

2023-02-02 21:43 UTC, ciscoLegrand commented on app/views/customers/_form.html.erb
> +        <%= form.number_field :pickup_price, step: :any, placeholder: 'Introduce el precio de recogida', class:'w-1/2 mx-auto block py-2.5 px-0 w-full text-lg text-slate-700 bg-transparent border-0 b
@lucas94gv  e o de seleccionar pickyp que non sea readonly?? dame algun dato mais, captura ou comentame na linea de codigo please

2023-02-02 21:55 UTC, lucas94gv commented on app/views/customers/index.html.erb
> +            <div class="flex flex-1 justify-center items center">
@ciscoLegrand correcto

2023-02-02 21:56 UTC, lucas94gv commented on app/views/customers/_form.html.erb
> +        <%= form.number_field :pickup_price, step: :any, placeholder: 'Introduce el precio de recogida', class:'w-1/2 mx-auto block py-2.5 px-0 w-full text-lg text-slate-700 bg-transparent border-0 b
@ciscoLegrand mañan si queres facemos chamada e revisamos antes de mergear porque creo que se pode quitar, na seguinte pr explico mais, fagoa ahora en nada

2023-02-02 22:23 UTC, ciscoLegrand commented on app/views/customers/_form.html.erb
> +        <%= form.number_field :pickup_price, step: :any, placeholder: 'Introduce el precio de recogida', class:'w-1/2 mx-auto block py-2.5 px-0 w-full text-lg text-slate-700 bg-transparent border-0 b
@lucas94gv perfect!! maña revisamos! que che queria comentar si esto dos precios se podria facer polimorfico pa usar un modelo percio en todolos sitios que fagan falta sin ter que andar a meter novos campos na db.

podria estar ben o enfoque ou vai coma o carallo???😅

2023-03-14 20:07 UTC, ciscoLegrand requested changes
@lucas94gv tres cuartos de lo mismo, eso resolvechelo na polimorfica asique se pode eliminar non??

2023-03-14 20:24 UTC, lucas94gv commented
@ciscoLegrand penso que si, pero non as elimines por ahora que tampouco molestan. Despois de esta v1 fago revision das ramas

2023-05-30 18:03 UTC, ciscoLegrand commented
implemented!

2023-05-30 18:03 UTC, closed without merging