Feature#delivery price by zone
CreadixGal/aeksion pull request #110
Opened 2023-02-02 22:05 UTC by lucas94gv

Set price on rates with delivery_price by zone

2023-02-02 22:07 UTC, lucas94gv commented
@ciscoLegrand al mergear unifico esos ifs en develop. Tambien se podria quitar el campo price de rates ya que al final se coge siempre de zones o customers. Mañana si puedes revisamos

2023-02-02 22:26 UTC, ciscoLegrand reviewed
_

2023-03-14 20:06 UTC, ciscoLegrand requested changes
@lucas94gv esta PR podese eliminar?? resolvechelo na polimorfica entendo

2023-03-14 20:06 UTC, ciscoLegrand commented on app/controllers/rates_controller.rb
> +    @rate.price = @rate.zone.delivery_price if @rate.delivery?
@lucas94gv esta pr e pa eliiminar non¿?

2023-05-30 18:03 UTC, ciscoLegrand commented
implemented!

2023-05-30 18:03 UTC, closed without merging