Feature#api
CreadixGal/aeksion pull request #32
Opened 2022-11-23 21:33 UTC by lucas94gv

Only main methods

2022-11-23 21:37 UTC, lucas94gv commented
@ciscoLegrand puto rubocop, sempre me olvido !!! mañanasubo commit arreglando

2022-11-27 21:12 UTC, ciscoLegrand requested changes
@lucas94gv i like it!! estas orientando la api hacia cargar muchos datos por archivo no? 
💯 lo de usar upserts!!! 👍 
un par de observaciones para cambiar en los controllers si te parece bien 😄

2022-11-27 21:12 UTC, ciscoLegrand commented on app/controllers/api/v1/movements_controller.rb
> +        movement = Movement.find(params[:movements][0][:id])
@lucas94gv aqui entiendo que deberia ser params[:id] segun las rutas `api/v1/customers/:id`
para eliminar varios no seria mejor otra acción en plan `def multiple_deletes` o algo asi en donde se le pasen en el body los ids como lo tines hecho

2022-11-30 20:29 UTC, lucas94gv commented on app/controllers/api/v1/movements_controller.rb
> +        movement = Movement.find(params[:movements][0][:id])
@ciscoLegrand la funcion basica de la api la cumpla, los cambios que comentas ya contaba con ellos. Cerramos esto para subir a devel lo basico que funciona y creo rama nueva para esto

2022-11-30 20:31 UTC, ciscoLegrand commented on app/controllers/api/v1/movements_controller.rb
> +        movement = Movement.find(params[:movements][0][:id])
@lucas94gv nice work!! 😄

2022-11-30 20:32 UTC, ciscoLegrand reviewed
@lucas94gv great!!!

2022-11-30 20:32 UTC, ciscoLegrand approved these changes

2022-11-30 20:33 UTC, merged